/* mkelos.c -- a length-of-stay table with the shape of the 2011 model, and a truth we choose.
 *
 * Copyright (c) 2001-2026 Vasili Gavrilov. BSD 2-Clause; see LICENSE.
 *
 * The deployed predictor was 24 binary procedure indicators plus a per-group intercept, fitted by
 * least squares against days of stay. That shape is what this generates: same column count, same
 * sparsity, same per-group intercepts. What varies is the TRUTH underneath, because the question
 * the two programs are here to settle is which of them to reach for, and that depends entirely on
 * whether the truth is a line.
 *
 *     ./mkelos --linear       LOS = intercept + sum of procedure costs        (a line is exact)
 *     ./mkelos --saturating   the same, but each further procedure adds less  (a line is wrong)
 *     ./mkelos --interaction  two procedures together cost more than apart    (a line is wrong)
 *
 * The noise is Gamma-shaped rather than Gaussian, because length of stay is a skewed,
 * non-negative, count-like response and a symmetric error would flatter both programs equally
 * and mislead about both. Its standard deviation is printed in the header comment of the file,
 * so the best attainable RMSE is known before either program runs.
 *
 * SYNTHETIC. No real data is in this repository, and none of these coefficients is fitted to
 * anything. The point is a table of the right SHAPE, not a table of real patients.
 *
 *     cc -std=c99 -W -Wall -O2 -o mkelos mkelos.c ../c/rng.c -lm
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

#include "../c/rng.h"

#define NPROC   24                   /* procedure indicators, as in the 2011 model */
#define NGROUP  8
#define NROW    600                  /* per group */

static double uni(Rng *r)
{
    return (double)rng_u32(r) / 4294967296.0;
}

/* Gamma(shape k, scale t) by summing exponentials when k is an integer, which it is here. A
 * length of stay is bounded below by zero and has a long right tail; a Gaussian has neither. */
static double gam(Rng *r, int k, double t)
{
    double s = 0;
    int i;
    for (i = 0; i < k; i++) {
        double u = uni(r);
        if (u < 1e-12) u = 1e-12;
        s += -log(u);
    }
    return s * t;
}

int main(int argc, char **argv)
{
    static double cost[NGROUP][NPROC], base[NGROUP];
    const char *mode = "linear";
    Rng r;
    int g, j, i;
    /* Gamma(4, 0.5): mean 2 days of noise, SD 1.0, skewed right. */
    const int    GK = 4;
    const double GT = 0.5;
    const double NOISE_SD = 1.0;

    for (i = 1; i < argc; i++) {
        if (!strcmp(argv[i], "--linear"))           mode = "linear";
        else if (!strcmp(argv[i], "--saturating"))  mode = "saturating";
        else if (!strcmp(argv[i], "--interaction")) mode = "interaction";
        else { fprintf(stderr, "mkelos: unknown option %s\n", argv[i]); return 2; }
    }

    /* One seed per mode, so each file is reproducible and the three are not the same rows. */
    rng_seed(&r, !strcmp(mode, "linear") ? 20260813u
                : !strcmp(mode, "saturating") ? 20260814u : 20260815u);

    /* Per-group intercepts and sparse costs: about a third of the procedures matter in a group,
     * which is the sparsity the deployed table had. */
    for (g = 0; g < NGROUP; g++) {
        base[g] = 2.0 + 6.0 * uni(&r);
        for (j = 0; j < NPROC; j++)
            cost[g][j] = uni(&r) < 0.35 ? 1.0 + 15.0 * uni(&r) : 0.0;
    }

    printf("# example/elos-%s.csv: a length-of-stay table in the shape of the 2011 model.\n", mode);
    printf("# SYNTHETIC, generated by example/mkelos.c --%s. Fitted to nothing.\n", mode);
    printf("#\n");
    printf("# %d groups x %d rows, %d binary procedure indicators, one per column.\n",
           NGROUP, NROW, NPROC);
    printf("# The response is days of stay. The noise is Gamma(%d, %.1f), so its SD is %.1f and\n",
           GK, GT, NOISE_SD);
    printf("# no fit of any kind can beat an RMSE of %.1f on this file.\n", NOISE_SD);
    printf("#\n");
    if (!strcmp(mode, "linear"))
        printf("# TRUTH: los = intercept + sum of the costs of the procedures present. A LINE IS\n"
               "# EXACT here, and linearr should reach the noise floor while bpnn should not.\n");
    else if (!strcmp(mode, "saturating"))
        printf("# TRUTH: the same costs, but the total saturates as 12*s/(4+s) where s is the raw\n"
               "# sum. The fifth procedure adds far less than the first, which is what a long stay\n"
               "# actually does. A line is the wrong shape.\n");
    else
        printf("# TRUTH: the same costs, plus a term for the two procedures 6 and 13 occurring\n"
               "# TOGETHER, which costs more than either apart. A line cannot see it, and linearr's\n"
               "# residual check can only report that some pair interacts, not which.\n");
    printf("group,los");
    for (j = 0; j < NPROC; j++) printf(",p%02d", j);
    printf("\n");

    for (g = 0; g < NGROUP; g++) {
        for (i = 0; i < NROW; i++) {
            int on[NPROC];
            double sum = 0, los;
            for (j = 0; j < NPROC; j++) {
                on[j] = uni(&r) < 0.18;          /* a case carries a handful of procedures */
                if (on[j]) sum += cost[g][j];
            }
            if (!strcmp(mode, "linear"))
                los = base[g] + sum;
            else if (!strcmp(mode, "saturating"))
                los = base[g] + 12.0 * sum / (4.0 + sum);
            else
                los = base[g] + sum + (on[6] && on[13] ? 9.0 : 0.0);
            los += gam(&r, GK, GT) - (double)GK * GT;   /* centred, so the mean is the truth */
            printf("%03d,%.4f", g + 1, los);
            for (j = 0; j < NPROC; j++) printf(",%d", on[j]);
            printf("\n");
        }
    }
    return 0;
}
