/* mknonlinear.c -- generate the non-linear counterpart of linearr's train.csv.
 *
 * linearr ships a training file that is SYNTHETIC and exactly linear, so that its fitter can be
 * checked against an answer known in advance. This is the same idea pointed the other way: a file
 * whose generating function is written down here, is deliberately not linear, and carries a known
 * amount of irreducible noise. That last part is what makes it a test rather than a demonstration.
 * Because the noise SD is 1.0 by construction, no model of any kind can do better than an RMSE of
 * 1.0 on held-out rows, so both programs can be scored against the floor instead of only against
 * each other. A network that reports 1.1 is close to optimal; one that reports 0.4 on training rows
 * has memorised, and its held-out column will say so.
 *
 * THE GENERATING FUNCTION, in the shape of a length-of-stay model because that is where linearr
 * came from:
 *
 *     los = 2.0
 *         + 14.0 * (1 - exp(-dose / 2.5))        a dose response that saturates
 *         + 0.04 * age                            plain linear in age
 *         + 0.10 * dose * max(0, age - 60) / 10   an interaction present only in older patients
 *         + N(0, 1)
 *
 * Two of those three terms are invisible to a straight line in dose and age. The saturation means
 * the first unit of dose does far more than the eighth, and a line has to average the two. The
 * interaction means the effect of dose depends on age, and a model with one coefficient per term
 * has no way to say that. So the residuals of the best possible straight line still depend on dose,
 * which is exactly the condition linearr's --residuals check tests for and reports.
 *
 * There is nothing medical here. The numbers are invented, they are fitted to nothing, and no
 * clinical conclusion survives contact with them. They exist so that the two fitters can be
 * compared on a relation whose true shape is known.
 *
 *     cc -std=c99 -W -Wall -O2 -o mknonlinear mknonlinear.c ../rng.c -lm
 *     ./mknonlinear > nonlinear.csv
 *
 * Deterministic: same seed, same file, on any machine, which is the property that makes the bench
 * reproducible.
 */
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>

#include "../rng.h"

#define NPER 400   /* rows per group */

/* Box-Muller, from the engine's PRNG, so the file regenerates identically. */
static double gauss(Rng *r)
{
    static int have = 0;
    static double spare;
    double u, v, s;
    if (have) { have = 0; return spare; }
    do {
        u = 2.0 * ((double)rng_u32(r) / 4294967296.0) - 1.0;
        v = 2.0 * ((double)rng_u32(r) / 4294967296.0) - 1.0;
        s = u * u + v * v;
    } while (s >= 1.0 || s == 0.0);
    s = sqrt(-2.0 * log(s) / s);
    spare = v * s; have = 1;
    return u * s;
}

static double uniform(Rng *r, double lo, double hi)
{
    return lo + (hi - lo) * ((double)rng_u32(r) / 4294967296.0);
}

/* the truth, without the noise */
static double truth(double dose, double age, double base)
{
    double older = age > 60.0 ? age - 60.0 : 0.0;
    return base
         + 14.0 * (1.0 - exp(-dose / 2.5))
         + 0.04 * age
         + 0.10 * dose * older / 10.0;
}

/* A SECOND relation, for the case that defeats the escalation pipeline rather than showing it off.
 * Here the response is a pure product of two inputs, each drawn symmetrically about zero:
 *
 *     y = x1 * x2 + N(0, 1)
 *
 * The best straight line through this has a slope of zero in BOTH terms, and, crucially, the
 * residuals it leaves have no marginal dependence on either term either, because averaged over a
 * symmetric x2 the effect of x1 is exactly zero. So a per-term curvature check finds nothing to
 * report even though a line explains none of the response. This is a false negative for any
 * escalation rule that reads such a check: the line looks blameless and is useless. It is here to
 * be measured, because a pipeline's failure mode is worth more than its demonstration.
 */
static double truth_inter(double x1, double x2)
{
    return x1 * x2;
}

int main(int argc, char **argv)
{
    Rng r;
    int g, i;
    int inter = (argc > 1 && !strcmp(argv[1], "--interaction"));
    static const char *name[2] = { "001", "002" };
    static const double base[2] = { 2.0, 5.0 };   /* the groups differ by an offset only */

    rng_seed(&r, inter ? 20260813u : 20260812u);

    if (inter) {
        printf("# example/interaction.csv: the case that defeats the escalation pipeline.\n");
        printf("#\n");
        printf("# SYNTHETIC. y = x1*x2 + N(0,1), with x1 and x2 drawn symmetrically about zero.\n");
        printf("# Generated by example/mknonlinear.c --interaction; see truth_inter() there.\n");
        printf("#\n");
        printf("# A straight line explains nothing here (its slope is zero in both terms) and yet\n");
        printf("# leaves residuals with no per-term curvature to detect, so linearr's residual\n");
        printf("# check stays silent and scripts/escalate.sh will NOT escalate. A network fits it.\n");
        printf("# The noise is N(0,1), so 1.0 is again the best achievable held-out RMSE.\n");
        printf("group,y,x1,x2\n");
        for (g = 0; g < 2; g++)
            for (i = 0; i < NPER; i++) {
                double x1 = uniform(&r, -5.0, 5.0);
                double x2 = uniform(&r, -5.0, 5.0);
                printf("%s,%.4f,%.4f,%.4f\n", name[g], truth_inter(x1, x2) + gauss(&r), x1, x2);
            }
        return 0;
    }

    printf("# example/nonlinear.csv: the non-linear counterpart of linearr's train.csv.\n");
    printf("#\n");
    printf("# SYNTHETIC and deliberately NOT linear. Generated by example/mknonlinear.c, whose\n");
    printf("# header states the generating function in full. Two of its terms are invisible to a\n");
    printf("# straight line: a dose response that saturates, and an interaction that appears only\n");
    printf("# in patients over 60.\n");
    printf("#\n");
    printf("# The noise is N(0,1) by construction, so an RMSE of 1.0 on held-out rows is the best\n");
    printf("# any model can do and both fitters can be scored against that floor. Nothing here is\n");
    printf("# medical: the numbers are invented and fitted to nothing.\n");
    printf("group,los,dose,age\n");
    for (g = 0; g < 2; g++) {
        for (i = 0; i < NPER; i++) {
            double dose = uniform(&r, 0.0, 10.0);
            double age  = uniform(&r, 20.0, 90.0);
            double los  = truth(dose, age, base[g]) + gauss(&r);
            printf("%s,%.4f,%.4f,%.2f\n", name[g], los, dose, age);
        }
    }
    return 0;
}
